### ISSUE TITLE
Add Grid Button on the Notebook Toolbar

### ISSUE THREAD

**Issue by firezym** [parmentelat/jupyterlab-gridwidth#1]
This implementation is so fantastic, which is just what I need for presentation and code/output comparison.

I suggest to bind the commands to grid button/drop down list on the notebook toolbar, so that the users do not need to remember commands or go to command list to click. The user friendly interface could improve usage of this awesome extension. (BTW, the chrome in windows has already taken the Ctrl+Num hotkeys.)

I drafted a dropdown list concept interface FIY :) It just looks like the drop down list for switching cell type between code and markdown. Hope it could be implemented on this awesome extension :P

![image](https://github.com/parmentelat/jupyterlab-gridwidth/assets/3654421/b625bff2-4e9c-4ed6-9224-8ff19f2f6a0e)

**Comment by parmentelat** [comment]
I just realized that, as the result of a copy & paste from a former extension, the current code has a provision in `plugin.json` for a boolean flag configurable in the settings editor
rather than cleaning this up I think it's best if we keep it, and recycle it so users can choose to have their menubar clobbered with the dropdown or not

**Comment by parmentelat** [comment]
done in #5 and available in 0.1.4
