### ISSUE TITLE
Split does not take effect in the newest jupyterlab 4.1.2

### ISSUE THREAD

**Issue by firezym** [parmentelat/jupyterlab-gridwidth#14]
In the newest jupyterlab 4.1.2, the cell metadata is changed, but the visual effect does not show:
![image](https://github.com/parmentelat/jupyterlab-gridwidth/assets/3654421/0ec8b54e-e682-4221-b985-72bcee5ee39f)

**Comment by firezym** [comment]
@parmentelat Please check if you have the same issue :) Some of my extensions have unexpected displaying behavior too...

**Comment by parmentelat** [comment]
hey @firezym 
now that you mention it I do see this problem in some of my virtual envs too
I won't be in a position to closely look into this in the very near future, but what I have seen on one failing instance is 
- the css class is properly set by jupyterlab-celltagsclasses 
- however the corresponding css rule does not seem to have been loaded
- and curiously enough - this might be a red herring but it's troubling - I see at least one other rule being applied twice - see attached; the level_intermediate thingy is a tag/class defined in another extension that also uses jupyterlab-celltagsclasses

because all the css files show up as simply `base.css` it's hard to see at first glance what's going on; however I would start with rebuilding the jupyter lab app just in case it helps ?

<img width="1702" alt="image" src="https://github.com/parmentelat/jupyterlab-gridwidth/assets/4519227/f10a0507-e049-4674-84a4-971e0653c3f8">

**Comment by firezym** [comment]
@parmentelat thanks! There is some important bug fix updates in jupyterlab 4.1.12. Do we really need to rebuild the gridwidth app? I think this broken thing issue is universal for a lot of extensions. Should we submit such issues to the jupyterlab repo?

**Comment by parmentelat** [comment]
this should be fixed in version 0.3.0 to be reeased shortly

**Comment by parmentelat** [comment]
It's available right away at pypi

**Comment by firezym** [comment]
I did not see any code change in this repo. Is it open source or does it just need a repack on the most recent jupyterlab extension backbone?

**Comment by parmentelat** [comment]
hey - sorry I had not pushed the recent commits - that's done now
however the latest release has been published on pypi a few days ago
https://pypi.org/project/jupyterlab-gridwidth/
